---
name: "ci"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  strategy:
    name: strategy
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate matrix
        id: matrix
        run: |
          echo "$(make list | grep ^bin/ | jq -nR '[inputs | select(length>0)]')" >>"$GITHUB_OUTPUT"

  build:
    name: build.${{ matrix }}
    runs-on: ubuntu-latest
    needs: strategy
    strategy:
      matrix: ${{fromJson(needs.strategy.outputs.matrix)}}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          make "${{ matrix }}"
      
      - name: List built artifacts
        run: |
          ls -l bin/